# Hyprland configuration

# Source config files
source = ~/.config/hypr/config/monitors.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/env_variables.conf
source = ~/.config/hypr/config/keybindings.conf
source = ~/.config/hypr/config/windowrules.conf
